name: Testes Automátizados

on: 
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Instalar Dependencia
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Rodar arquivo
        run: |
          python -m pytest tests/
