name: Testes Automátizados

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: action/checkout@v2

      -name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

      -name: Instalar Dependencia
      run: |
          python -m pip install --upgrade pip
          pip install flask
      
      -name: Rodar arquivo
      run: |
      pip install pytest

      python -m pytest tests/
